site_name: Clean Architecture con Python
pages:
    - Inicio: index.md
    - Introducción:
        - Inicio: introduccion/index.md
    - Beneficios:
        - Inicio: beneficios/index.md
    - Fundamentos:
        - Inicio: fundamentos/index.md
    - Implementación:
        - Inicio: implementacion/index.md
    - Sobre:
        - Nosotros: sobre/nubark.md
        - Licencia: sobre/licencia.md
theme: material
